dist: xenial
language: python
python:
  - "3.6"
  - "3.7"
install:
  - pip install --upgrade pip setuptools wheel cython
  - pip install -r requirements.txt
  - pip install flake8
before_script:
script:
  - flake8
after_success:
